//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baker_ido
{
    public partial class all
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}
